apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws-credentials
  namespace: prashant
spec:
  podIdentity:
    provider: aws
    roleArn: arn:aws:iam::877009927033:role/keda-nginx-sqs-reader
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: aws-sqs-queue-scaledobject
  namespace: prashant
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
      name: keda-trigger-auth-aws-credentials
    metadata:
      queueURL: https://sqs.ap-south-1.amazonaws.com/877009927033/prashant
      queueLength: "5"
      awsRegion: "ap-south-1"
      scaleOnInFlight: "false"
