apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws-credentials
  namespace: prashant
spec:
  podIdentity:
    provider: aws
    roleArn: arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/consumer-sqs-keda
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: aws-sqs-queue-scaledobject
  namespace: prashant
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
      name: keda-trigger-auth-aws-credentials
    metadata:
      queueURL: https://sqs.{{AWS_REGION}}.amazonaws.com/{{AWS_ACCOUNT_ID}}/{{QUEUE_NAME}}
      queueLength: "5"
      awsRegion: "{{AWS_REGION}}"
      scaleOnInFlight: "false"
